### ISSUE TITLE
Get local IP with sockets - Enhancement for host.py

### ISSUE THREAD

**Issue by nrxss** [Tortle6/Multiplayer-TicTacToe#1]
Since you can automatically get the local IP address of the host with `socket.gethostbyname(socket.gethostname())` , I am suggesting to update line 20 of *host.py* to
```
IP = socket.gethostbyname(socket.gethostname())
print(IP)
```
so the user will not have to do `ipconfig` and search for their local IP in command prompt every time they want to connect

**Comment by AlexanderJCS** [comment]
Thanks for pointing this out. I have updated the code.
